// This is just an example,
// so you can safely delete all default props below

export default {
  failed: 'Action failed',
  success: 'Action was successful',
  nav: { home: 'Home', valueChains: 'Value Chains Analyzer', sectoral: 'Sectoral GVC Analysis', about: 'About', health: 'Health Sector', overview: 'Overview', gvcOverview: 'GVC overview', participation: 'Participation in GVCs', backward: 'Backward linkages', forward: 'Forward linkages', briefs: 'Economy Briefs' },
  va: {
    menu: 'Menu', resources: 'Resources', technicalNotes: 'Technical Notes', userGuide: 'User Guide', demoVideos: 'Demo Videos', downloadData: 'Download Data', comingSoon: 'Coming soon',
    title: 'Value Chains Analyzer', intro: 'Gain insight into your economy\'s participation in global value chains (GVCs). Uncover the sources of intermediate inputs and destinations of domestic value-added.',
    cards: {
      gvc: { title: 'How is your economy connected through value chains?', content: 'Explore key trade and production linkages to get an overview of how your economy participates in global value chains.' },
      participation: { title: 'How does your economy\'s value-added structure connect with the rest of the world?', content: 'Measure your economy\'s overall integration into GVCs.' },
      backward: { title: 'Where do imported inputs used in your economy\'s exports come from?', content: 'Explore your economy\'s reliance on upstream partners in global value chains.' },
      forward: { title: 'Where does your economy contribute the most towards exports elsewhere?', content: 'Follow your value-added as it becomes part of other economies\' exports or supply chains.' },
      briefs: { title: 'How does your economy perform in global value chains?', content: 'Get a snapshot of your economy\'s GVC performance with charts, comparisons, and summaries.' }
    }
  },
  economyBrief: {
    economy: 'Economy', download: 'Download', preparing: 'Preparing...',
    shareAction: 'SHARE', sharePage: 'Share this page', shareCustomized: 'You can share this customized view of {page}', copied: 'Copied to clipboard',
    guideHtml: `<h2>How to interpret this Economy Brief?</h2><p>This Economy Brief summarizes how an economy is integrated into Global Value Chains (GVCs) through <strong>backward</strong> and <strong>forward</strong> linkages. Results are shown as shares of gross exports (%) and values in USD millions or billions to highlight both the relative importance and magnitude of each linkage.</p><h3>1) GVC overview: Backward vs. Forward linkages</h3><ul><li><strong>Backward linkages (Foreign value added in exports)</strong> indicate how much of the economy's exports rely on imported inputs.</li><li><strong>Forward linkages (Domestic value added in foreign exports)</strong> indicate how much domestic value added is used in other economies' exports. The overview shows the direction of value-added flows, while trend charts show how these linkages evolve.</li></ul><h3>2) Top 5 GVC sectors</h3><p>This section highlights the five sectors that contribute most to:</p><ul><li><strong>Backward linkages</strong> — sectors most dependent on foreign inputs in exports.</li><li><strong>Forward linkages</strong> — sectors whose value added is most used in foreign exports. Stacked bars show sector composition and values in USD millions or billions.</li></ul><h3>3) Top 5 GVC partners</h3><p>This section highlights the five partner economies that:</p><ul><li>contribute the largest foreign value added embodied in the economy's exports, and</li><li>use the largest domestic value added from the economy in their exports.</li></ul><p>Stacked bars compare partner composition over time, with values shown in USD millions or billions.</p>`
  },
  backward: {
    title: 'Backward Linkages', viewBy: 'View by', chooseFocus: 'Choose your main focus',
    shareAction: 'SHARE', sharePage: 'Share this page', shareCustomized: 'You can share this customized view of {page}', copied: 'Copied to clipboard',
    exportingSector: 'Exporting Sector', sourceEconomy: 'Source Economy', exportingEconomy: 'Exporting economy', importingEconomy: 'Importing economy',
    periodStart: 'Period start', periodEnd: 'Period end', apply: 'Apply',
    sameEconomyError: 'The exporting economy cannot be the same as the importing economy.',
    yearRangeError: 'Period end must be a year after the Period start. Please select a valid range.',
    limitedData: 'Limited data available', availability: '{exporting} - {importing} is available only for {start}–{end}.', availabilityWithSource: '{exporting} - {importing} (source: {source}) is available only for {start}–{end}.',
    adjustPeriod: 'Please adjust Period start/end within this range and apply again.',
    applied: 'Your changes have been applied. Scroll down to review the results.',
    policyTitle: 'Key policy questions (select by exporting sector)',
    sourcePolicyTitle: 'Key policy questions (select by source economy)',
    sourcePolicyQuestionOne: "How is foreign value-added distributed across {economy}'s exporting sectors?",
    sourcePolicyQuestionGeneric: "How is foreign value-added distributed across the economy's exporting sectors?",
    allSectors: 'All sectors', year: 'Year', exploreYear: 'View detailed trade linkages for a selected year',
    policyQuestionOne: "Where does the economy's imported content used in its exports come from?",
    policyQuestionTwo: 'How does this compare across economies in the same region?',
    policyQuestionNamed: "Where does {economy}'s imported content used in its exports come from?",
    summaryTitle: "Where does {economy}'s imported content come from?",
    summaryDescription: "Some part of {economy}'s gross exports consists of imported inputs that originate in other source economies.",
    world: 'World',
    charts: {
      sourceRegionYears: 'Source region across years', sourceRegionPeriods: 'Source region across periods', topSourceYears: 'Top source economy across years', topSourcePeriods: 'Top source economy across periods', topExportingYears: 'Top exporting sector across years', topExportingPeriods: 'Top exporting sector across periods', bySource: 'Backward linkages by source economy', bySector: 'Backward linkages by exporting sector', byYear: 'Backward linkages by year', backwardIn: 'Backward linkages in {region} economies',
      noTrade: 'No trade occurred under the selected settings', tryDifferent: 'Try a different year range, sector, or economy pair.', tryDifferentEconomy: 'Try a different year range or economy selection.', preparing: 'Preparing the visualization', rendering: 'Rendering the chart and finalizing the display.', patience: 'Thank you for your patience.', viewLess: 'View less', viewMore: 'View more', breakdown: 'Click here to see the breakdown', close: 'CLOSE',
      percentBackward: 'Percent of Backward Linkages', percentGrossTo: 'Percent of gross exports to {economy}', year: 'Year', share: 'Share', value: 'Value', million: 'million', billion: 'billion', ofBackward: 'of backward linkages',
      regionsTitle: "Which regions are the main sources of Foreign Value Added (FVA) embedded in {exporting}'s {sector} exports to {importing}?", topTitle: "Which economies are the top sources of Foreign Value Added (FVA) embedded in {exporting}'s {sector} exports to {importing}?", sourceTitle: "Where does {exporting}'s Foreign Value Added (FVA) in exports of {sector} to {importing} come from?", periodTitle: "Where does {exporting}'s imported content in exports of {sector} to {importing} come from?", regionTitle: "Where do {region} economies' imported content in exports of {sector} to {importing} come from?", totalPeriods: 'Total backward linkages amounted to USD {firstValue} in {firstPeriod} and USD {secondValue} in {secondPeriod}.',
      regionAsia: 'Asia-Pacific', regionEurope: 'Europe', regionNorthAmerica: 'North America', regionLatinAmerica: 'Latin America', regionRestWorld: 'Rest of the World', others: 'Others',
      unchanged: 'unchanged', upBy: 'up by {value} percentage points', downBy: 'down by {value} percentage points',
      topYearDescription: "{share}% of {exporting}'s {sector} FVA was sourced from {source} in {end}, {change} since {start}.",
      topPeriodDescription: "During {current}, {exporting}'s backward linkages sourced from {source} accounted for {share}%, {change} compared with {previous}.",
      regionYearDescription: "{share}% of {exporting}'s FVA is sourced from {region}, {change} since {start}.",
      regionPeriodDescription: "During {current}, {share}% of {exporting}'s {sector} FVA was sourced from {region}, {change} compared with {previous}.",
      regionalTop: '{source} was the top regional source economy, accounting for {share}% of total FVA in {year}.',
      sourceSubtitle: "Gross exports of {exporting} in {sector} to {importing} amounted to {gross} in {year}. Of these exports, {fva} is foreign value added sourced from other economies. By region, Asia-Pacific accounts for {asia}%, followed by Europe ({europe}%), North America ({northAmerica}%), Latin America ({latinAmerica}%), and the Rest of the World ({restWorld}%). The largest country-level contributors are {contributors}.",
      sourceSectorTitle: "In which exporting sectors is {source}'s value-added content most embedded in {exporting}'s exports to {importing}?",
      sourceSectorSingleTitle: "How is {source}'s value-added in {exporting}'s exports to {importing} distributed across sectors?",
      sourceSectorSubtitle: "Gross exports of {exporting} to {importing} amount to {gross} in {year}. Of these exports, {backward} is imported content that comes from {source}, mainly used in the following exporting sectors in {exporting}: {sectors}.",
      sourceRegionTitle: "How is {source}'s value-added distributed across the sectoral exports of {region} economies to {importing}?",
      sourceYearDescription: "{share}% of {source}'s value-added content in {exporting}'s exports to {importing} is exported via the {sector} sector, {change} since {start}.",
      sourcePeriodDescription: "During {period}, {share}% of {source}'s value-added content in {exporting}'s exports to {importing} was exported via the {sector} sector{comparison}.", comparedWith: 'compared with {period}'
    }
  },
  forward: {
    title: 'Forward Linkages', shareAction: 'SHARE', sharePage: 'Share this page', shareCustomized: 'You can share this customized view of {page}', copied: 'Copied to clipboard', viewBy: 'View by', chooseFocus: 'Choose your main focus', exportingSector: 'Exporting Sector', importingEconomyFocus: 'Importing Economy', exportingEconomy: 'Exporting economy', importingEconomy: 'Importing economy', thirdEconomy: 'Third economy', periodStart: 'Period start', periodEnd: 'Period end', apply: 'Apply', year: 'Year', allSectors: 'All sectors',
    yearRangeError: 'Period end must be a year after the Period start. Please select a valid range.', limitedData: 'Limited data available', availability: '{economy} is available only for {start}–{end}.', adjustPeriod: 'Please adjust Period start/end within this range and apply again.', applied: 'Your changes have been applied. Scroll down to review the results.',
    sectorPolicyTitle: 'Key policy questions (select by exporting sector)', sectorPolicyOne: 'Where does {economy} contribute the most towards export production?', importPolicyTitle: 'Key policy questions (select by importing economy)', importPolicyOne: 'Which sectors in {economy} contribute the most to export production in the selected importing economy?', compareRegion: 'How does this compare across economies in the same region?', compareExporters: 'How does this compare across exporting economies from the same region?', summaryTitle: 'Where does {economy} contribute towards export production?', summaryDescription: "This analysis traces {economy}'s Domestic Value Added (DVA) used in other economies' exports.", importSummaryTitle: 'Which sectors in {economy} contribute to export production in {importing}?',
    byYear: 'Forward linkages by year', exploreYear: 'View detailed trade linkages for a selected year', byImporter: 'Forward linkages by importing economy', bySector: 'Forward linkages by exporting sector', inRegion: 'Forward linkages in {region} economies', regionYears: 'Region across years', regionPeriods: 'Region across periods', topEconomiesYears: 'Top economies across years', topEconomiesPeriods: 'Top economies across periods', topSectorsYears: 'Top five exporting sectors in {exporting} to {importing} across years', topSectorsPeriods: 'Top five exporting sectors in {exporting} to {importing} across periods',
    preparing: 'Preparing the visualization', rendering: 'Rendering the chart and finalizing the display.', patience: 'Thank you for your patience.', noTrade: 'No trade occurred under the selected settings', tryDifferent: 'Try a different year range, sector, or economy selection.', viewLess: 'View less', viewMore: 'View more', percentForward: 'Percent of Forward Linkages', percentGrossTo: 'Percent of gross exports to {economy}', share: 'Share', value: 'Value', million: 'million', billion: 'billion', ofForward: 'of forward linkages', world: 'world', clickBar: 'Click on a bar to see the individual economies associated with a region',
    sectorContributionTitle: "How is {exporting}'s contribution to export production in {importing} distributed across sectors?", regionContributionTitle: "How are {region} economies' contributions to export production in {importing} distributed across sectors?", destinationTitle: "Where does {exporting} contribute the most towards export production?", regionDestinationTitle: 'Where do {region} economies contribute the most towards export production ({sector})?', topSectorTitle: 'Which exporting sectors in {exporting} contribute the most to further export production in {importing}?', topSectorPeriodsTitle: "Which exporting sectors in {exporting} contribute most to {importing}'s export production across periods?", topDestinationTitle: "Which economies are the primary destinations for {exporting}'s forward linkages in {sector} exports?", destinationShiftTitle: "How has the destination of {exporting}'s {sector} forward linkages shifted over time?", regionForwardTitle: "In which regions do {exporting}'s forward linkages in {sector} exports go?", regionForwardPeriodsTitle: "In which regions do {exporting}'s forward linkages in {sector} exports go across periods?", countrySectorTitle: "How is {country}'s contribution to export production in {importing} distributed across sectors?", countryDestinationTitle: 'Where does {country} contribute the most towards export production ({sector})?',
    destinationYearDescription: "{share}% of {exporting}'s forward linkages in {sector} exports go to {destination}, {change} since {start}.", destinationPeriodDescription: "During {current}, {share}% of {exporting}'s forward linkages in {sector} exports went to {destination}, {change} compared with {previous}.", sectorYearDescription: "{sector} exports represent {share}% of {exporting}'s domestic value added used for further export production in {importing}, {change} since {start}.", sectorPeriodDescription: "During {current}, {sector} represented {share}% of {exporting}'s value added used for further export production in {importing}, {change} compared with {previous}.", topRegionalDestination: '{economy} is the top regional destination, accounting for {share}% of intermediate exports to GVCs.', importerSubtitle: "Gross exports of {exporting} in {sector} to the world amounted to {gross} in {year}. Of these exports, {forward} is domestic value added used in other economies' exports.", sectorSubtitle: 'Gross exports of {exporting} to {importing} amounted to {gross} in {year}. The contribution used for further export production was {forward}.'
  },
  gvc: {
    title: 'GVC Overview', exportingEconomy: 'Exporting economy', periodStart: 'Period start', periodEnd: 'Period end', apply: 'Apply', year: 'Year',
    yearRangeError: 'Period end must be a year after the Period start. Please select a valid range.', limitedData: 'Limited data available', availability: '{economy} is available only for {start}–{end}.', adjustPeriod: 'Please adjust Period start/end within this range and apply again.', applied: 'Your changes have been applied. Scroll down to review the results.',
    policyTitle: 'Key policy questions', policyOne: "How much of a role do imports from abroad play in an economy's export production? (backward linkages)", policyTwo: 'Which exporting sectors in this economy rely the most on imported content from other economies? (backward linkages)', policyThree: "Which economies contribute the most towards this economy's exports? (backward linkages)", policyFour: "How much does an economy's value-added in exports contribute to export production in other economies? (forward linkages)", policyFive: 'Which exporting sectors in this economy contribute the most to export production in other economies? (forward linkages)', policySix: "Which economies are most dependent on this economy's exports for their own export production? (forward linkages)",
    acrossYears: 'GVC Overview Across Years', acrossPeriods: 'GVC overview across periods', topSectorsPeriods: 'Top 5 GVC sectors across periods', topPartnersPeriods: 'Top 5 GVC partners across periods', overviewByYear: 'GVC overview by year', exploreYear: 'Explore detailed linkages in a specific year', overview: 'GVC overview',
    backward: 'Backward Linkages', forward: 'Forward Linkages', grossExports: 'Gross Exports', viewLess: 'View less', viewMore: 'View more', fvaExports: "Foreign value added (FVA) in {economy}'s exports", dvaExports: "{economy}'s value added (DVA) in exports", dvaForeignExports: "{economy}'s value added in foreign exports",
    chartYearsTitle: "How have {economy}'s GVC linkages evolved over the years?", chartPeriodsTitle: "How do {economy}'s GVC linkages compare across different periods?", percentGross: "Percent of {economy}'s Gross exports", period: 'Period', share: 'Share', value: 'Value', million: 'million', billion: 'billion', usdMillion: 'USD Million', usdBillion: 'USD Billion', ofGross: 'of gross exports',
    backwardYearDescription: "In {lastYear}, {current}% of {economy}'s gross exports embedded FVA from abroad, {direction} from {previous}% in {firstYear}.", forwardYearDescription: "In {lastYear}, {economy}'s DVA was {current}% of gross exports, {direction} from {previous}% in {firstYear}.", increased: 'increased', decreased: 'decreased',
    periodDescription: "Between {first} and {second}, the share of {linkage} in {economy}'s gross exports {direction} from {firstShare}% to {secondShare}%, equivalent to ${firstValue}B and ${secondValue}B respectively.", foreignValueAdded: 'foreign value added', exportedInputs: "{economy}'s exports used as inputs in other economies' exports",
    overviewTitle: "{economy}'s Gross Exports: Backward vs Forward Linkages ({year})", backwardDefinition: "Backward linkages refer to foreign value added (FVA) produced abroad and used in {economy}'s exports. In {year}, FVA accounted for {share}% of gross exports, valued at USD {value}.", forwardDefinition: "Forward linkages represent {economy}'s domestic value added (DVA) subsequently embedded in partner economies' exports. In {year}, forward linkages made up {share}% of gross exports, equivalent to USD {value}.",
    topSectorBack: 'Top 5 Backward-Linked Exporting Sectors', topSectorFor: 'Top 5 Forward-Linked Exporting Sectors', topPartnerBack: 'Top 5 Backward-Linked Partner economies', topPartnerFor: 'Top 5 Forward-Linked Partner economies', totalGrossSubtitle: 'Total gross exports of {economy} in {year}: USD {value}', sectorGrossExports: 'in sectoral gross exports', foreignValueAxis: 'Foreign value-added ({unit})', partnerContributionAxis: 'Contribution to partner exports ({unit})', shareAction: 'SHARE', sharePage: 'Share this page', shareCustomized: 'You can share this customized view of {page}', copied: 'Copied to clipboard',
    breakdown: 'Click here to break down', close: 'Close',
    partnerBackDescription: "In {year}, {economy}'s exports incorporated USD {value} in foreign inputs from {partner}, accounting for {share}% of {economy}'s gross exports.",
    partnerForDescription: "In {year}, {economy}'s exports contributed USD {value} to {partner}'s export production, accounting for {share}% of {economy}'s gross exports.",
    sectorBackDescription: "In {year}, {economy}'s {sector} exports included USD {value} in FVA, accounting for {share}% of the sector's total export value.",
    sectorForDescription: "In {year}, {economy}'s {sector} exports contributed USD {value} in DVA that was subsequently embedded in partners' exports. This DVA accounts for {share}% of the sector's gross exports."
  },
  participation: {
    title: 'Participation in GVCs', shareAction: 'SHARE', sharePage: 'Share this page', shareCustomized: 'You can share this customized view of {page}', copied: 'Copied to clipboard',
    viewBy: 'View by', exportingEconomy: 'Exporting economy', importingEconomy: 'Importing economy', periodStart: 'Period start', periodEnd: 'Period end', apply: 'Apply',
    sameEconomyError: 'The exporting economy cannot be the same as the importing economy.', yearRangeError: 'Period end must be a year after the Period start. Please select a valid range.',
    limitedData: 'Limited data available', availability: '{exporting} - {importing} is available only for {start}–{end}.', adjustPeriod: 'Please adjust Period start/end within this range and apply again.', applied: 'Your changes have been applied. Scroll down to review the results.',
    policyTitle: 'Key policy questions', policyOne: "How are an economy's gross exports generated and where are they ultimately used?", policyTwo: "How does the economy's trade balance look when measured in value-added terms compared to gross exports?", policyThree: "What share of this economy's gross exports is attributable to GVCs?",
    byYear: 'Participation in GVCs by year', exploreYear: 'View detailed trade linkages for a selected year', year: 'Year',
    valueAddedBreakdown: 'Value-added breakdown', noTrade: 'No trade occurred under the selected settings', viewLess: 'View less', viewMore: 'View more', acrossYears: 'GVC Participation across years',
    grossAndValueTradeBalance: 'Gross and value added trade balance', grossTradeBalance: 'Gross Trade Balance', valueAddedTradeBalance: 'Value Added Trade Balance', percentGross: 'Percent of gross exports', percentBilateral: 'Percent of bilateral gross trade', percentagesRounding: 'Percentages may not total 100% because of rounding.',
    gvcRelated: 'GVC-related Value Added Exports', directConsumption: 'Direct Consumption Value Added Exports', share: 'Share', value: 'Value', million: 'million', billion: 'billion', ofGross: 'of gross exports', ofBilateral: 'of bilateral gross trade',
    dvaIntermediate: 'DVA intermediate goods', dvaFinal: 'DVA final goods', dvaBack: 'DVA intermediate goods exports back to original exporter', dvaThird: 'DVA intermediate goods exported to a third economy', fva: 'Foreign Value Added (FVA)', doubleCounted: 'Double-counted value',
    allSectors: 'All sectors', exporter: 'Exporter', partnerEconomy: 'partner economy', breakdown: 'Click here to see the breakdown', close: 'CLOSE', world: 'World',
    productionYearsTitle: "How have {exporting}'s exports of {sector} to {importing} been produced and utilized over the years?", productionTitle: "How have {exporting}'s exports of {sector} to {importing} been produced and utilized?", exportsSubtitle: "{exporting}'s gross exports to {importing}: ${partnerValue} | {exporting}'s gross exports to {world}: ${worldValue}.",
    gvcTrendTitle: "How has the share of {exporting}'s GVC-related exports of {sector} to {importing} changed over time?", balanceTrendTitle: "How has {exporting}'s gross and value-added trade balance with {importing} across {sector} changed over the years?", balanceTitle: "How does {exporting}'s gross and value-added trade balance in {sector} with {importing} differ?", structureIn: 'Structure of value added in {region}', regionTitle: "How have {region} economies' exports of {sector} to {importing} been produced and utilized?", percentGrossTo: 'Percent of gross exports to {economy}',
    descIntermediate: "Domestic value added (DVA) in intermediate goods destined for final consumption in {importing} represented {share} of {exporting}'s gross exports in {sector} to {importing} in {year}.", descFinal: "Domestic value added (DVA) in final goods destined for final consumption in {importing} represented {share} of {exporting}'s gross exports in {sector} to {importing} in {year}.", descBack: "DVA in intermediate goods re-exported by {importing} back to {exporting} represented {share} of {exporting}'s gross exports in {sector} to {importing} in {year}.", descThird: "DVA in intermediate goods re-exported by {importing} to a third economy represented {share} of {exporting}'s gross exports in {sector} to {importing} in {year}.", descFva: "Foreign value added (FVA) in {exporting}'s exports to {importing} represented {share} of gross exports in {sector} in {year}.", descDouble: "Double-counted value due to repeated border crossings represented {share} of {exporting}'s gross exports in {sector} to {importing} in {year}.",
    gvcSummary: "In {year}, {share}% of {exporting}'s gross exports to {importing} was attributable to GVCs. This GVC-related share consists of:", gvcForward: "{share}% was {exporting}'s DVA embedded in {importing}'s re-exports to third economies (forward linkages).", gvcReturned: "{share}% was {exporting}'s DVA embedded in {importing}'s re-exports back to {exporting}.", gvcFva: "{share}% reflected FVA embedded in {exporting}'s gross exports to {importing}.", gvcDouble: '{share}% was double-counted value due to repeated border crossings.', directSummary: "In {year}, {share}% of {exporting}'s gross exports to {importing} represented DVA consumed within the export destination.", intermediateExports: '{share}% was intermediate exports.', finalExports: '{share}% was final exports.',
    grossImportsExceeded: "In {year}, {partner}'s gross imports from {reporter} exceeded its exports by {share}% of bilateral gross trade.", grossExportsExceeded: "In {year}, {partner}'s gross exports to {reporter} exceeded its imports by {share}% of bilateral gross trade.", grossEqual: "In {year}, {partner}'s gross exports to {reporter} equaled its imports.", vaHigher: "In {year}, {partner}'s exported value added to {reporter} was {share}% higher than its imported value added.", vaLower: "In {year}, {partner}'s exported value added to {reporter} was {share}% lower than its imported value added.", vaEqual: "In {year}, {partner}'s imported value added from {reporter} equaled its exported value added."
  },
  home: {
    heroTitle: 'Understand Value Chains.\nExplore Sector-Level Insights.',
    heroDescription: 'RIVA helps you analyze economy-level value chains, sector dynamics, chokepoints, and bilateral trade relationships to inform evidence-based policy and strengthen economic resilience.',
    explore: 'Explore how value added flows across borders', dive: 'Dive deep into specific sectors to analyze', scroll: 'Scroll to explore',
    waysTitle: 'Two ways to Explore Value Chains', waysSubtitle: 'Choose the experience that best fits your needs',
    valueDescription: 'Explore economy-level value chains, cross-border linkages, and overall participation in global value chains (GVCs).', sectorDescription: 'Dive deep into specific sectors to analyze sectoral dynamics, chokepoints, and bilateral trade relationships.',
    useTitle: 'Use RIVA to...', readyTitle: 'Ready to explore the data?', readyDescription: 'Start your analysis today and uncover the insights that drive resilient and inclusive economies.',
    cards: [
      ['Understand how economies connect through value chains', 'Explore how economies participate in global value chains through trade, production linkages, and cross-border flows. RIVA helps you see where value is created, where inputs come from, and how economies are connected across the region and beyond.'],
      ['Build analysis around the data that matters', 'Select indicators and design indices to meet your needs. RIVA allows you to compare integration across economies, sectors, and time, while focusing on the issues most relevant to you.'],
      ['Explore sector-level value chain insights', 'Dive deeper into specific sectors to understand value chain positions, dependencies, chokepoints, and product-level trade patterns. Sectoral Analysis supports strategic sector insights, starting with Health and expandable to future sectors.'],
      ['Identify opportunities for stronger regional cooperation', 'Discover bilateral relationships, supply dependencies, and opportunities for stronger cooperation. RIVA helps highlight where economies can strengthen resilience, diversify partners, and support evidence-based policy decisions.']
    ],
    health: { title: 'Health Value Chains', intro: 'Sector-level analysis of the Health value chain to identify key players, critical chokepoints, and bilateral trade relationships that drive resilience and access to essential health products', cards: [['GVC Position', 'Access a country’s position in the global Health value chain.'], ['Chokepoints', 'Identify critical points of vulnerability and supply chain risks.'], ['Bilateral Relationship', 'Explore bilateral trade relationships in Health products and inputs.'], ['Product Detail', 'Analyze detailed trade flows and product-level insights.']] }
  },
  footer: {
    terms: 'Terms of Use',
    disclaimerTitle: 'DISCLAIMER:',
    disclaimer: 'RIVA is powered by the Trade, Investment and Innovation Division of the United Nations Economic and Social Commission for Asia and the Pacific. For questions, please contact us at {email}.',
    termsIntro: 'All users may publish information taken directly from, or derived from, the platform under the following conditions:',
    termsOne: 'The platform must be acknowledged and cited as ESCAP RIVA, with the access date (e.g., September 2025), and made available at',
    termsTwo: 'Any conclusions or analyses based on the data and visualizations provided must be accompanied by a disclaimer stating that they are the responsibility of the authors and do not necessarily reflect the views of the United Nations.',
    termsThree: 'Any re-dissemination of downloaded data by third parties beyond the scope of analytical publication must receive prior approval from the United Nations Secretariat.',
    requests: 'Requests can be sent to:',
    division: 'Trade, Investment and Innovation Division',
    unEscap: 'United Nations ESCAP',
    email: 'Email:'
  }
}
