/**
 * Sector names keyed by catID from va/get_sector.php.
 * Add a new catID here whenever the PHP API introduces a new sector.
 */
export const sectorTranslations = {
  "en-US": {
    0: "All sectors", 1: "Agriculture, hunting, forestry, and fishing", 2: "Mining and quarrying", 3: "Food, beverages, and tobacco", 4: "Textiles and textile products", 5: "Leather, leather products, and footwear", 6: "Wood and products of wood and cork", 7: "Pulp, paper, paper products, printing, and publishing", 8: "Coke, refined petroleum, and nuclear fuel", 9: "Chemicals and chemical products", 10: "Rubber and plastics", 11: "Other nonmetallic minerals", 12: "Basic metals and fabricated metal", 13: "Machinery, nec", 14: "Electrical and optical equipment", 15: "Transport equipment", 16: "Manufacturing, nec; recycling", 17: "Electricity, gas, and water supply", 18: "Construction", 19: "Sale, maintenance, and repair of motor vehicles and motorcycles; retail sale of fuel", 20: "Wholesale trade and commission trade, except of motor vehicles and motorcycles", 21: "Retail trade, except of motor vehicles and motorcycles; repair of household goods", 22: "Hotels and restaurants", 23: "Inland transport", 24: "Water transport", 25: "Air transport", 26: "Other supporting and auxiliary transport activities; activities of travel agencies", 27: "Post and telecommunications", 28: "Financial intermediation", 29: "Real estate activities", 30: "Renting of M&Eq and other business activities", 31: "Public administration and defense; compulsory social security", 32: "Education", 33: "Health and social work", 34: "Other community, social, and personal services", 35: "Private households with employed persons",
  },
  "zh-CN": {
    0: "所有行业", 1: "农业、狩猎、林业和渔业", 2: "采矿和采石", 3: "食品、饮料和烟草", 4: "纺织品和纺织产品", 5: "皮革、皮革制品和鞋类", 6: "木材及木材和软木制品", 7: "纸浆、纸张、纸制品、印刷和出版", 8: "焦炭、精炼石油和核燃料", 9: "化学品和化工产品", 10: "橡胶和塑料", 11: "其他非金属矿物", 12: "基础金属和金属制品", 13: "机械设备（未另分类）", 14: "电气和光学设备", 15: "运输设备", 16: "制造业（未另分类）；回收", 17: "电力、燃气和供水", 18: "建筑业", 19: "机动车和摩托车销售、维修及燃料零售", 20: "批发和佣金贸易（不含机动车和摩托车）", 21: "零售贸易（不含机动车和摩托车）；家用物品维修", 22: "酒店和餐饮", 23: "陆路运输", 24: "水路运输", 25: "航空运输", 26: "其他运输辅助活动及旅行社活动", 27: "邮政和电信", 28: "金融中介", 29: "房地产业", 30: "机械设备租赁及其他商业活动", 31: "公共管理和国防；强制性社会保障", 32: "教育", 33: "卫生和社会工作", 34: "其他社区、社会和个人服务", 35: "雇佣人员的私人家庭",
  },
  "ru-RU": {
    0: "Все отрасли", 1: "Сельское хозяйство, охота, лесное хозяйство и рыболовство", 2: "Добыча полезных ископаемых", 3: "Пищевые продукты, напитки и табак", 4: "Текстиль и текстильные изделия", 5: "Кожа, изделия из кожи и обувь", 6: "Древесина и изделия из древесины и пробки", 7: "Целлюлоза, бумага, бумажные изделия, полиграфия и издательское дело", 8: "Кокс, нефтепродукты и ядерное топливо", 9: "Химикаты и химическая продукция", 10: "Резина и пластмассы", 11: "Прочие неметаллические минералы", 12: "Основные металлы и металлоизделия", 13: "Машины и оборудование, не включенные в другие категории", 14: "Электрическое и оптическое оборудование", 15: "Транспортное оборудование", 16: "Производство, не включенное в другие категории; переработка", 17: "Электро-, газо- и водоснабжение", 18: "Строительство", 19: "Продажа, обслуживание и ремонт автомобилей и мотоциклов; розничная продажа топлива", 20: "Оптовая и комиссионная торговля, кроме автомобилей и мотоциклов", 21: "Розничная торговля, кроме автомобилей и мотоциклов; ремонт бытовых товаров", 22: "Гостиницы и рестораны", 23: "Наземный транспорт", 24: "Водный транспорт", 25: "Воздушный транспорт", 26: "Вспомогательная транспортная деятельность и туристические агентства", 27: "Почта и телекоммуникации", 28: "Финансовое посредничество", 29: "Операции с недвижимостью", 30: "Аренда машин и оборудования и другие деловые услуги", 31: "Государственное управление и оборона; обязательное социальное обеспечение", 32: "Образование", 33: "Здравоохранение и социальная работа", 34: "Прочие коммунальные, социальные и персональные услуги", 35: "Частные домохозяйства с наемными работниками",
  },
  "fr-FR": {
    0: "Tous les secteurs", 1: "Agriculture, chasse, sylviculture et pêche", 2: "Activités extractives", 3: "Produits alimentaires, boissons et tabac", 4: "Textiles et produits textiles", 5: "Cuir, articles en cuir et chaussures", 6: "Bois et produits du bois et du liège", 7: "Pâte à papier, papier, produits en papier, imprimerie et édition", 8: "Coke, produits pétroliers raffinés et combustible nucléaire", 9: "Produits chimiques", 10: "Caoutchouc et plastiques", 11: "Autres minéraux non métalliques", 12: "Métaux de base et ouvrages en métal", 13: "Machines et équipements, n.c.a.", 14: "Équipements électriques et optiques", 15: "Matériel de transport", 16: "Fabrication, n.c.a.; recyclage", 17: "Électricité, gaz et distribution d’eau", 18: "Construction", 19: "Vente, entretien et réparation de véhicules automobiles et motocycles; vente au détail de carburant", 20: "Commerce de gros et intermédiaires du commerce, sauf automobiles et motocycles", 21: "Commerce de détail, sauf automobiles et motocycles; réparation d’articles domestiques", 22: "Hôtels et restaurants", 23: "Transport terrestre", 24: "Transport par eau", 25: "Transport aérien", 26: "Activités auxiliaires des transports et agences de voyage", 27: "Postes et télécommunications", 28: "Intermédiation financière", 29: "Activités immobilières", 30: "Location de machines et équipements et autres services aux entreprises", 31: "Administration publique et défense; sécurité sociale obligatoire", 32: "Éducation", 33: "Santé et action sociale", 34: "Autres services collectifs, sociaux et personnels", 35: "Ménages privés employant du personnel",
  },
};

export const sectorGroupTranslations = {
  "en-US": {
    manufacturingLow: "Manufacturing Low tech", manufacturingHighMedium: "Manufacturing High and medium tech", services: "Services", Agriculture: "Agriculture", Mining: "Mining", Construction: "Construction", Utilities: "Utilities", "Manufacturing Low tech": "Manufacturing Low tech", "Manufacturing High and medium tech": "Manufacturing High and medium tech", "Services Trade and repair": "Trade and repair services", "Services Tourism": "Tourism services", "Services Transport": "Transport services", "Services ICT": "ICT services", "Services Property and business": "Property and business services", "Services Financial": "Financial services", "Services Public and welfare": "Public and welfare services", "Services Private household": "Private household services"
  },
  "zh-CN": {
    manufacturingLow: "低技术制造业", manufacturingHighMedium: "中高技术制造业", services: "服务业", Agriculture: "农业", Mining: "采矿业", Construction: "建筑业", Utilities: "公用事业", "Manufacturing Low tech": "低技术制造业", "Manufacturing High and medium tech": "中高技术制造业", "Services Trade and repair": "贸易和维修服务", "Services Tourism": "旅游服务", "Services Transport": "运输服务", "Services ICT": "信息通信技术服务", "Services Property and business": "房地产和商业服务", "Services Financial": "金融服务", "Services Public and welfare": "公共和福利服务", "Services Private household": "私人家庭服务"
  },
  "ru-RU": {
    manufacturingLow: "Низкотехнологичное производство", manufacturingHighMedium: "Средне- и высокотехнологичное производство", services: "Услуги", Agriculture: "Сельское хозяйство", Mining: "Добывающая промышленность", Construction: "Строительство", Utilities: "Коммунальные услуги", "Manufacturing Low tech": "Низкотехнологичное производство", "Manufacturing High and medium tech": "Средне- и высокотехнологичное производство", "Services Trade and repair": "Торговля и ремонт", "Services Tourism": "Туристические услуги", "Services Transport": "Транспортные услуги", "Services ICT": "Услуги ИКТ", "Services Property and business": "Недвижимость и деловые услуги", "Services Financial": "Финансовые услуги", "Services Public and welfare": "Государственные и социальные услуги", "Services Private household": "Услуги частных домохозяйств"
  },
  "fr-FR": {
    manufacturingLow: "Industries manufacturières de faible technologie", manufacturingHighMedium: "Industries manufacturières de moyenne et haute technologie", services: "Services", Agriculture: "Agriculture", Mining: "Activités extractives", Construction: "Construction", Utilities: "Services publics", "Manufacturing Low tech": "Industries manufacturières de faible technologie", "Manufacturing High and medium tech": "Industries manufacturières de moyenne et haute technologie", "Services Trade and repair": "Commerce et réparation", "Services Tourism": "Services touristiques", "Services Transport": "Services de transport", "Services ICT": "Services TIC", "Services Property and business": "Immobilier et services aux entreprises", "Services Financial": "Services financiers", "Services Public and welfare": "Services publics et sociaux", "Services Private household": "Services des ménages privés"
  },
};

/** Returns a translated sector label, keeping the PHP category as a fallback. */
export const translateSector = ({ catID, category }, locale = "en-US") =>
  sectorTranslations[locale]?.[String(catID)] || sectorTranslations["en-US"]?.[String(catID)] || category;

export const translateSectorGroup = (key, locale = "en-US") =>
  sectorGroupTranslations[locale]?.[key] || sectorGroupTranslations["en-US"]?.[key] || key;
